# Generated by Django 5.1.7 on 2025-03-08 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tag_lesson_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pre_course',
            field=models.ManyToManyField(null=True, to='courses.course'),
        ),
        migrations.CreateModel(
            name='UserLessonView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveIntegerField(default=0)),
                ('reading_date', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='viewers',
            field=models.ManyToManyField(through='courses.UserLessonView', to=settings.AUTH_USER_MODEL),
        ),
    ]
