# Generated by Django 5.1.7 on 2025-03-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_myuser_cvonline_alter_lesson_viewers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pre_course',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
